### ISSUE TITLE
A bug in 'addRectangularObstacle' function

### ISSUE THREAD

**Issue by purewater0901** [kohonda/mppi_playground#1]
Thank you for sharing the code! This is a great example of MPPI with Pytorch and GPU.

When I ran the code, I found a bag in the code [here](https://github.com/kohonda/mppi_playground/blob/main/src/envs/obstacle_map_2d.py#L146-L150). I think the following code can fix the problem.

```
x_init = center_occ[0] - ceil(width_occ / 2)
x_end = center_occ[0] + ceil(width_occ / 2)
y_init = center_occ[1] - ceil(height_occ / 2)
y_end = center_occ[1] + ceil(height_occ / 2)
```

**Comment by kohonda** [comment]
@purewater0901 
I fixed it. Thanks!
